package com.example.demo.model;

import java.util.Date;

public class AssetFirewall {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.host_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.host_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.host_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.office_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.enabled
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.manufacturer
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.host_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.mac
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String mac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.mac_last_change
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date macLastChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.online
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Boolean online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.snmp_community
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String snmpCommunity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.result
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.cpu_usage_rate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Float cpuUsageRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_firewall.memory_usage_rate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Float memoryUsageRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.id
     *
     * @return the value of asset_firewall.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.id
     *
     * @param id the value for asset_firewall.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.name
     *
     * @return the value of asset_firewall.name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.name
     *
     * @param name the value for asset_firewall.name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.host_name
     *
     * @return the value of asset_firewall.host_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.host_name
     *
     * @param hostName the value for asset_firewall.host_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.host_ip
     *
     * @return the value of asset_firewall.host_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostIp() {
        return hostIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.host_ip
     *
     * @param hostIp the value for asset_firewall.host_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostIp(String hostIp) {
        this.hostIp = hostIp == null ? null : hostIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.project_id
     *
     * @return the value of asset_firewall.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.project_id
     *
     * @param projectId the value for asset_firewall.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.host_id
     *
     * @return the value of asset_firewall.host_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.host_id
     *
     * @param hostId the value for asset_firewall.host_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostId(String hostId) {
        this.hostId = hostId == null ? null : hostId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.office_id
     *
     * @return the value of asset_firewall.office_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getOfficeId() {
        return officeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.office_id
     *
     * @param officeId the value for asset_firewall.office_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOfficeId(String officeId) {
        this.officeId = officeId == null ? null : officeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.status
     *
     * @return the value of asset_firewall.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.status
     *
     * @param status the value for asset_firewall.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.enabled
     *
     * @return the value of asset_firewall.enabled
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.enabled
     *
     * @param enabled the value for asset_firewall.enabled
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.manufacturer
     *
     * @return the value of asset_firewall.manufacturer
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.manufacturer
     *
     * @param manufacturer the value for asset_firewall.manufacturer
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.host_port
     *
     * @return the value of asset_firewall.host_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostPort() {
        return hostPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.host_port
     *
     * @param hostPort the value for asset_firewall.host_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostPort(String hostPort) {
        this.hostPort = hostPort == null ? null : hostPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.create_by
     *
     * @return the value of asset_firewall.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.create_by
     *
     * @param createBy the value for asset_firewall.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.create_date
     *
     * @return the value of asset_firewall.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.create_date
     *
     * @param createDate the value for asset_firewall.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.update_by
     *
     * @return the value of asset_firewall.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.update_by
     *
     * @param updateBy the value for asset_firewall.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.update_date
     *
     * @return the value of asset_firewall.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.update_date
     *
     * @param updateDate the value for asset_firewall.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.remarks
     *
     * @return the value of asset_firewall.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.remarks
     *
     * @param remarks the value for asset_firewall.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.del_flag
     *
     * @return the value of asset_firewall.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.del_flag
     *
     * @param delFlag the value for asset_firewall.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.org_id
     *
     * @return the value of asset_firewall.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.org_id
     *
     * @param orgId the value for asset_firewall.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.mac
     *
     * @return the value of asset_firewall.mac
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.mac
     *
     * @param mac the value for asset_firewall.mac
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.mac_last_change
     *
     * @return the value of asset_firewall.mac_last_change
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getMacLastChange() {
        return macLastChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.mac_last_change
     *
     * @param macLastChange the value for asset_firewall.mac_last_change
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setMacLastChange(Date macLastChange) {
        this.macLastChange = macLastChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.description
     *
     * @return the value of asset_firewall.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.description
     *
     * @param description the value for asset_firewall.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.online
     *
     * @return the value of asset_firewall.online
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Boolean getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.online
     *
     * @param online the value for asset_firewall.online
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOnline(Boolean online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.snmp_community
     *
     * @return the value of asset_firewall.snmp_community
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSnmpCommunity() {
        return snmpCommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.snmp_community
     *
     * @param snmpCommunity the value for asset_firewall.snmp_community
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSnmpCommunity(String snmpCommunity) {
        this.snmpCommunity = snmpCommunity == null ? null : snmpCommunity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.result
     *
     * @return the value of asset_firewall.result
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.result
     *
     * @param result the value for asset_firewall.result
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.cpu_usage_rate
     *
     * @return the value of asset_firewall.cpu_usage_rate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Float getCpuUsageRate() {
        return cpuUsageRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.cpu_usage_rate
     *
     * @param cpuUsageRate the value for asset_firewall.cpu_usage_rate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCpuUsageRate(Float cpuUsageRate) {
        this.cpuUsageRate = cpuUsageRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_firewall.memory_usage_rate
     *
     * @return the value of asset_firewall.memory_usage_rate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Float getMemoryUsageRate() {
        return memoryUsageRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_firewall.memory_usage_rate
     *
     * @param memoryUsageRate the value for asset_firewall.memory_usage_rate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setMemoryUsageRate(Float memoryUsageRate) {
        this.memoryUsageRate = memoryUsageRate;
    }
}