package com.example.demo.model;

import java.util.Date;

public class AssetMysql {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.host_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.host_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.host_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.office_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.enabled
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.manufacturer
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.host_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_mysql.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.id
     *
     * @return the value of asset_mysql.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.id
     *
     * @param id the value for asset_mysql.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.name
     *
     * @return the value of asset_mysql.name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.name
     *
     * @param name the value for asset_mysql.name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.host_name
     *
     * @return the value of asset_mysql.host_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.host_name
     *
     * @param hostName the value for asset_mysql.host_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.host_ip
     *
     * @return the value of asset_mysql.host_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostIp() {
        return hostIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.host_ip
     *
     * @param hostIp the value for asset_mysql.host_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostIp(String hostIp) {
        this.hostIp = hostIp == null ? null : hostIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.project_id
     *
     * @return the value of asset_mysql.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.project_id
     *
     * @param projectId the value for asset_mysql.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.host_id
     *
     * @return the value of asset_mysql.host_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.host_id
     *
     * @param hostId the value for asset_mysql.host_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostId(String hostId) {
        this.hostId = hostId == null ? null : hostId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.office_id
     *
     * @return the value of asset_mysql.office_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getOfficeId() {
        return officeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.office_id
     *
     * @param officeId the value for asset_mysql.office_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOfficeId(String officeId) {
        this.officeId = officeId == null ? null : officeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.status
     *
     * @return the value of asset_mysql.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.status
     *
     * @param status the value for asset_mysql.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.enabled
     *
     * @return the value of asset_mysql.enabled
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.enabled
     *
     * @param enabled the value for asset_mysql.enabled
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.manufacturer
     *
     * @return the value of asset_mysql.manufacturer
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.manufacturer
     *
     * @param manufacturer the value for asset_mysql.manufacturer
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.host_port
     *
     * @return the value of asset_mysql.host_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostPort() {
        return hostPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.host_port
     *
     * @param hostPort the value for asset_mysql.host_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostPort(String hostPort) {
        this.hostPort = hostPort == null ? null : hostPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.create_by
     *
     * @return the value of asset_mysql.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.create_by
     *
     * @param createBy the value for asset_mysql.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.create_date
     *
     * @return the value of asset_mysql.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.create_date
     *
     * @param createDate the value for asset_mysql.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.update_by
     *
     * @return the value of asset_mysql.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.update_by
     *
     * @param updateBy the value for asset_mysql.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.update_date
     *
     * @return the value of asset_mysql.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.update_date
     *
     * @param updateDate the value for asset_mysql.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.remarks
     *
     * @return the value of asset_mysql.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.remarks
     *
     * @param remarks the value for asset_mysql.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.del_flag
     *
     * @return the value of asset_mysql.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.del_flag
     *
     * @param delFlag the value for asset_mysql.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.org_id
     *
     * @return the value of asset_mysql.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.org_id
     *
     * @param orgId the value for asset_mysql.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_mysql.description
     *
     * @return the value of asset_mysql.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_mysql.description
     *
     * @param description the value for asset_mysql.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}