package com.example.demo.model;

import java.util.Date;

public class Encoder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.ID
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.SBMC
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sbmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.SBBM
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sbbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.SBLX
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sblx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.IPAddress
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String ipaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.PORT
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.manufacturer_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String manufacturerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.SBCJ
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sbcj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.SSPGD
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sspgd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.SFGB
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer sfgb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.SBXH
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sbxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.TDS
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer tds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.TDQSXH
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer tdqsxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.GLPGMK
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String glpgmk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.SBQD
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sbqd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.LJXY
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String ljxy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.CSXY
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String csxy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.HYLX
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hylx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.WLBS
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String wlbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.SSXM
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String ssxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.CJDW
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String cjdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.user
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_domain
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipDomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_equipment_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipEquipmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_local_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipLocalPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_register_indate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipRegisterIndate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_heartbeat_period
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipHeartbeatPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_max_heartbeat_overtime
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipMaxHeartbeatOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.sip_administrative_divisions
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipAdministrativeDivisions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.access_module_identification_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String accessModuleIdentificationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.taskseq
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String taskseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.normal_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String normalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.build_owner
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String buildOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.project_type_point
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String projectTypePoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.longitude
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.latitude
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.install_site
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String installSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.result
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encoder.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer searchType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.ID
     *
     * @return the value of encoder.ID
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.ID
     *
     * @param id the value for encoder.ID
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.SBMC
     *
     * @return the value of encoder.SBMC
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSbmc() {
        return sbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.SBMC
     *
     * @param sbmc the value for encoder.SBMC
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc == null ? null : sbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.SBBM
     *
     * @return the value of encoder.SBBM
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSbbm() {
        return sbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.SBBM
     *
     * @param sbbm the value for encoder.SBBM
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSbbm(String sbbm) {
        this.sbbm = sbbm == null ? null : sbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.SBLX
     *
     * @return the value of encoder.SBLX
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSblx() {
        return sblx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.SBLX
     *
     * @param sblx the value for encoder.SBLX
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSblx(String sblx) {
        this.sblx = sblx == null ? null : sblx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.IPAddress
     *
     * @return the value of encoder.IPAddress
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.IPAddress
     *
     * @param ipaddress the value for encoder.IPAddress
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress == null ? null : ipaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.PORT
     *
     * @return the value of encoder.PORT
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.PORT
     *
     * @param port the value for encoder.PORT
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.manufacturer_id
     *
     * @return the value of encoder.manufacturer_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getManufacturerId() {
        return manufacturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.manufacturer_id
     *
     * @param manufacturerId the value for encoder.manufacturer_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setManufacturerId(String manufacturerId) {
        this.manufacturerId = manufacturerId == null ? null : manufacturerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.SBCJ
     *
     * @return the value of encoder.SBCJ
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSbcj() {
        return sbcj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.SBCJ
     *
     * @param sbcj the value for encoder.SBCJ
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSbcj(String sbcj) {
        this.sbcj = sbcj == null ? null : sbcj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.SSPGD
     *
     * @return the value of encoder.SSPGD
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSspgd() {
        return sspgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.SSPGD
     *
     * @param sspgd the value for encoder.SSPGD
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSspgd(String sspgd) {
        this.sspgd = sspgd == null ? null : sspgd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.SFGB
     *
     * @return the value of encoder.SFGB
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getSfgb() {
        return sfgb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.SFGB
     *
     * @param sfgb the value for encoder.SFGB
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSfgb(Integer sfgb) {
        this.sfgb = sfgb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.SBXH
     *
     * @return the value of encoder.SBXH
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSbxh() {
        return sbxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.SBXH
     *
     * @param sbxh the value for encoder.SBXH
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSbxh(String sbxh) {
        this.sbxh = sbxh == null ? null : sbxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.TDS
     *
     * @return the value of encoder.TDS
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getTds() {
        return tds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.TDS
     *
     * @param tds the value for encoder.TDS
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setTds(Integer tds) {
        this.tds = tds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.TDQSXH
     *
     * @return the value of encoder.TDQSXH
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getTdqsxh() {
        return tdqsxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.TDQSXH
     *
     * @param tdqsxh the value for encoder.TDQSXH
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setTdqsxh(Integer tdqsxh) {
        this.tdqsxh = tdqsxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.GLPGMK
     *
     * @return the value of encoder.GLPGMK
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getGlpgmk() {
        return glpgmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.GLPGMK
     *
     * @param glpgmk the value for encoder.GLPGMK
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setGlpgmk(String glpgmk) {
        this.glpgmk = glpgmk == null ? null : glpgmk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.SBQD
     *
     * @return the value of encoder.SBQD
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSbqd() {
        return sbqd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.SBQD
     *
     * @param sbqd the value for encoder.SBQD
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSbqd(String sbqd) {
        this.sbqd = sbqd == null ? null : sbqd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.LJXY
     *
     * @return the value of encoder.LJXY
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getLjxy() {
        return ljxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.LJXY
     *
     * @param ljxy the value for encoder.LJXY
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setLjxy(String ljxy) {
        this.ljxy = ljxy == null ? null : ljxy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.CSXY
     *
     * @return the value of encoder.CSXY
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCsxy() {
        return csxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.CSXY
     *
     * @param csxy the value for encoder.CSXY
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCsxy(String csxy) {
        this.csxy = csxy == null ? null : csxy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.HYLX
     *
     * @return the value of encoder.HYLX
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHylx() {
        return hylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.HYLX
     *
     * @param hylx the value for encoder.HYLX
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHylx(String hylx) {
        this.hylx = hylx == null ? null : hylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.WLBS
     *
     * @return the value of encoder.WLBS
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getWlbs() {
        return wlbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.WLBS
     *
     * @param wlbs the value for encoder.WLBS
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setWlbs(String wlbs) {
        this.wlbs = wlbs == null ? null : wlbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.SSXM
     *
     * @return the value of encoder.SSXM
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSsxm() {
        return ssxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.SSXM
     *
     * @param ssxm the value for encoder.SSXM
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSsxm(String ssxm) {
        this.ssxm = ssxm == null ? null : ssxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.CJDW
     *
     * @return the value of encoder.CJDW
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCjdw() {
        return cjdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.CJDW
     *
     * @param cjdw the value for encoder.CJDW
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCjdw(String cjdw) {
        this.cjdw = cjdw == null ? null : cjdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.create_by
     *
     * @return the value of encoder.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.create_by
     *
     * @param createBy the value for encoder.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.create_date
     *
     * @return the value of encoder.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.create_date
     *
     * @param createDate the value for encoder.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.update_by
     *
     * @return the value of encoder.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.update_by
     *
     * @param updateBy the value for encoder.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.update_date
     *
     * @return the value of encoder.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.update_date
     *
     * @param updateDate the value for encoder.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.remarks
     *
     * @return the value of encoder.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.remarks
     *
     * @param remarks the value for encoder.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.user
     *
     * @return the value of encoder.user
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.user
     *
     * @param user the value for encoder.user
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.password
     *
     * @return the value of encoder.password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.password
     *
     * @param password the value for encoder.password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.project_id
     *
     * @return the value of encoder.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.project_id
     *
     * @param projectId the value for encoder.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_number
     *
     * @return the value of encoder.sip_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipNumber() {
        return sipNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_number
     *
     * @param sipNumber the value for encoder.sip_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipNumber(String sipNumber) {
        this.sipNumber = sipNumber == null ? null : sipNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_domain
     *
     * @return the value of encoder.sip_domain
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipDomain() {
        return sipDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_domain
     *
     * @param sipDomain the value for encoder.sip_domain
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipDomain(String sipDomain) {
        this.sipDomain = sipDomain == null ? null : sipDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_ip
     *
     * @return the value of encoder.sip_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipIp() {
        return sipIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_ip
     *
     * @param sipIp the value for encoder.sip_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipIp(String sipIp) {
        this.sipIp = sipIp == null ? null : sipIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_port
     *
     * @return the value of encoder.sip_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipPort() {
        return sipPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_port
     *
     * @param sipPort the value for encoder.sip_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipPort(String sipPort) {
        this.sipPort = sipPort == null ? null : sipPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_equipment_number
     *
     * @return the value of encoder.sip_equipment_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipEquipmentNumber() {
        return sipEquipmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_equipment_number
     *
     * @param sipEquipmentNumber the value for encoder.sip_equipment_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipEquipmentNumber(String sipEquipmentNumber) {
        this.sipEquipmentNumber = sipEquipmentNumber == null ? null : sipEquipmentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_password
     *
     * @return the value of encoder.sip_password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipPassword() {
        return sipPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_password
     *
     * @param sipPassword the value for encoder.sip_password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipPassword(String sipPassword) {
        this.sipPassword = sipPassword == null ? null : sipPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_local_port
     *
     * @return the value of encoder.sip_local_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipLocalPort() {
        return sipLocalPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_local_port
     *
     * @param sipLocalPort the value for encoder.sip_local_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipLocalPort(String sipLocalPort) {
        this.sipLocalPort = sipLocalPort == null ? null : sipLocalPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_register_indate
     *
     * @return the value of encoder.sip_register_indate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipRegisterIndate() {
        return sipRegisterIndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_register_indate
     *
     * @param sipRegisterIndate the value for encoder.sip_register_indate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipRegisterIndate(String sipRegisterIndate) {
        this.sipRegisterIndate = sipRegisterIndate == null ? null : sipRegisterIndate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_heartbeat_period
     *
     * @return the value of encoder.sip_heartbeat_period
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipHeartbeatPeriod() {
        return sipHeartbeatPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_heartbeat_period
     *
     * @param sipHeartbeatPeriod the value for encoder.sip_heartbeat_period
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipHeartbeatPeriod(String sipHeartbeatPeriod) {
        this.sipHeartbeatPeriod = sipHeartbeatPeriod == null ? null : sipHeartbeatPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_max_heartbeat_overtime
     *
     * @return the value of encoder.sip_max_heartbeat_overtime
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipMaxHeartbeatOvertime() {
        return sipMaxHeartbeatOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_max_heartbeat_overtime
     *
     * @param sipMaxHeartbeatOvertime the value for encoder.sip_max_heartbeat_overtime
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipMaxHeartbeatOvertime(String sipMaxHeartbeatOvertime) {
        this.sipMaxHeartbeatOvertime = sipMaxHeartbeatOvertime == null ? null : sipMaxHeartbeatOvertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.sip_administrative_divisions
     *
     * @return the value of encoder.sip_administrative_divisions
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipAdministrativeDivisions() {
        return sipAdministrativeDivisions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.sip_administrative_divisions
     *
     * @param sipAdministrativeDivisions the value for encoder.sip_administrative_divisions
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipAdministrativeDivisions(String sipAdministrativeDivisions) {
        this.sipAdministrativeDivisions = sipAdministrativeDivisions == null ? null : sipAdministrativeDivisions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.access_module_identification_code
     *
     * @return the value of encoder.access_module_identification_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getAccessModuleIdentificationCode() {
        return accessModuleIdentificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.access_module_identification_code
     *
     * @param accessModuleIdentificationCode the value for encoder.access_module_identification_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setAccessModuleIdentificationCode(String accessModuleIdentificationCode) {
        this.accessModuleIdentificationCode = accessModuleIdentificationCode == null ? null : accessModuleIdentificationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.org_id
     *
     * @return the value of encoder.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.org_id
     *
     * @param orgId the value for encoder.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.del_flag
     *
     * @return the value of encoder.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.del_flag
     *
     * @param delFlag the value for encoder.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.taskseq
     *
     * @return the value of encoder.taskseq
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getTaskseq() {
        return taskseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.taskseq
     *
     * @param taskseq the value for encoder.taskseq
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setTaskseq(String taskseq) {
        this.taskseq = taskseq == null ? null : taskseq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.normal_code
     *
     * @return the value of encoder.normal_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getNormalCode() {
        return normalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.normal_code
     *
     * @param normalCode the value for encoder.normal_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setNormalCode(String normalCode) {
        this.normalCode = normalCode == null ? null : normalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.build_owner
     *
     * @return the value of encoder.build_owner
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getBuildOwner() {
        return buildOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.build_owner
     *
     * @param buildOwner the value for encoder.build_owner
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setBuildOwner(String buildOwner) {
        this.buildOwner = buildOwner == null ? null : buildOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.project_type_point
     *
     * @return the value of encoder.project_type_point
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProjectTypePoint() {
        return projectTypePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.project_type_point
     *
     * @param projectTypePoint the value for encoder.project_type_point
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProjectTypePoint(String projectTypePoint) {
        this.projectTypePoint = projectTypePoint == null ? null : projectTypePoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.longitude
     *
     * @return the value of encoder.longitude
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.longitude
     *
     * @param longitude the value for encoder.longitude
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.latitude
     *
     * @return the value of encoder.latitude
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.latitude
     *
     * @param latitude the value for encoder.latitude
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.install_site
     *
     * @return the value of encoder.install_site
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getInstallSite() {
        return installSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.install_site
     *
     * @param installSite the value for encoder.install_site
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setInstallSite(String installSite) {
        this.installSite = installSite == null ? null : installSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.result
     *
     * @return the value of encoder.result
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.result
     *
     * @param result the value for encoder.result
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.description
     *
     * @return the value of encoder.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.description
     *
     * @param description the value for encoder.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encoder.search_type
     *
     * @return the value of encoder.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getSearchType() {
        return searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encoder.search_type
     *
     * @param searchType the value for encoder.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }
}