package com.example.demo.model;

import java.util.Date;

public class Problem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.title
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.level
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.relate_event_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String relateEventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.relate_asset_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String relateAssetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.relate_asset_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String relateAssetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.happen_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date happenDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.recovery_event_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String recoveryEventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.recovery_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date recoveryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.work_order_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String workOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.host_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.host_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.host_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.host_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String hostPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.item_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem_data
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String problemData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.recovery_data
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String recoveryData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer searchType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.id
     *
     * @return the value of problem.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.id
     *
     * @param id the value for problem.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.title
     *
     * @return the value of problem.title
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.title
     *
     * @param title the value for problem.title
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.description
     *
     * @return the value of problem.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.description
     *
     * @param description the value for problem.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.level
     *
     * @return the value of problem.level
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.level
     *
     * @param level the value for problem.level
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.relate_event_id
     *
     * @return the value of problem.relate_event_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRelateEventId() {
        return relateEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.relate_event_id
     *
     * @param relateEventId the value for problem.relate_event_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRelateEventId(String relateEventId) {
        this.relateEventId = relateEventId == null ? null : relateEventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.relate_asset_type
     *
     * @return the value of problem.relate_asset_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRelateAssetType() {
        return relateAssetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.relate_asset_type
     *
     * @param relateAssetType the value for problem.relate_asset_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRelateAssetType(String relateAssetType) {
        this.relateAssetType = relateAssetType == null ? null : relateAssetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.relate_asset_id
     *
     * @return the value of problem.relate_asset_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRelateAssetId() {
        return relateAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.relate_asset_id
     *
     * @param relateAssetId the value for problem.relate_asset_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRelateAssetId(String relateAssetId) {
        this.relateAssetId = relateAssetId == null ? null : relateAssetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.happen_date
     *
     * @return the value of problem.happen_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getHappenDate() {
        return happenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.happen_date
     *
     * @param happenDate the value for problem.happen_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHappenDate(Date happenDate) {
        this.happenDate = happenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.recovery_event_id
     *
     * @return the value of problem.recovery_event_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRecoveryEventId() {
        return recoveryEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.recovery_event_id
     *
     * @param recoveryEventId the value for problem.recovery_event_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRecoveryEventId(String recoveryEventId) {
        this.recoveryEventId = recoveryEventId == null ? null : recoveryEventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.recovery_date
     *
     * @return the value of problem.recovery_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getRecoveryDate() {
        return recoveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.recovery_date
     *
     * @param recoveryDate the value for problem.recovery_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRecoveryDate(Date recoveryDate) {
        this.recoveryDate = recoveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.status
     *
     * @return the value of problem.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.status
     *
     * @param status the value for problem.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.work_order_id
     *
     * @return the value of problem.work_order_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getWorkOrderId() {
        return workOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.work_order_id
     *
     * @param workOrderId the value for problem.work_order_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setWorkOrderId(String workOrderId) {
        this.workOrderId = workOrderId == null ? null : workOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.host_ip
     *
     * @return the value of problem.host_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostIp() {
        return hostIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.host_ip
     *
     * @param hostIp the value for problem.host_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostIp(String hostIp) {
        this.hostIp = hostIp == null ? null : hostIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.host_name
     *
     * @return the value of problem.host_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.host_name
     *
     * @param hostName the value for problem.host_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.host_id
     *
     * @return the value of problem.host_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.host_id
     *
     * @param hostId the value for problem.host_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostId(String hostId) {
        this.hostId = hostId == null ? null : hostId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.host_port
     *
     * @return the value of problem.host_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHostPort() {
        return hostPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.host_port
     *
     * @param hostPort the value for problem.host_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHostPort(String hostPort) {
        this.hostPort = hostPort == null ? null : hostPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.item_id
     *
     * @return the value of problem.item_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.item_id
     *
     * @param itemId the value for problem.item_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.project_id
     *
     * @return the value of problem.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.project_id
     *
     * @param projectId the value for problem.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.org_id
     *
     * @return the value of problem.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.org_id
     *
     * @param orgId the value for problem.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem_data
     *
     * @return the value of problem.problem_data
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProblemData() {
        return problemData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem_data
     *
     * @param problemData the value for problem.problem_data
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProblemData(String problemData) {
        this.problemData = problemData == null ? null : problemData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.recovery_data
     *
     * @return the value of problem.recovery_data
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRecoveryData() {
        return recoveryData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.recovery_data
     *
     * @param recoveryData the value for problem.recovery_data
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRecoveryData(String recoveryData) {
        this.recoveryData = recoveryData == null ? null : recoveryData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.search_type
     *
     * @return the value of problem.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getSearchType() {
        return searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.search_type
     *
     * @param searchType the value for problem.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }
}