package com.example.demo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProblemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public ProblemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("`level` is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("`level` is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("`level` =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("`level` <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("`level` >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`level` >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("`level` <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("`level` <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("`level` like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("`level` not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("`level` in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("`level` not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("`level` between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("`level` not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdIsNull() {
            addCriterion("relate_event_id is null");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdIsNotNull() {
            addCriterion("relate_event_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdEqualTo(String value) {
            addCriterion("relate_event_id =", value, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdNotEqualTo(String value) {
            addCriterion("relate_event_id <>", value, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdGreaterThan(String value) {
            addCriterion("relate_event_id >", value, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdGreaterThanOrEqualTo(String value) {
            addCriterion("relate_event_id >=", value, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdLessThan(String value) {
            addCriterion("relate_event_id <", value, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdLessThanOrEqualTo(String value) {
            addCriterion("relate_event_id <=", value, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdLike(String value) {
            addCriterion("relate_event_id like", value, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdNotLike(String value) {
            addCriterion("relate_event_id not like", value, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdIn(List<String> values) {
            addCriterion("relate_event_id in", values, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdNotIn(List<String> values) {
            addCriterion("relate_event_id not in", values, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdBetween(String value1, String value2) {
            addCriterion("relate_event_id between", value1, value2, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateEventIdNotBetween(String value1, String value2) {
            addCriterion("relate_event_id not between", value1, value2, "relateEventId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeIsNull() {
            addCriterion("relate_asset_type is null");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeIsNotNull() {
            addCriterion("relate_asset_type is not null");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeEqualTo(String value) {
            addCriterion("relate_asset_type =", value, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeNotEqualTo(String value) {
            addCriterion("relate_asset_type <>", value, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeGreaterThan(String value) {
            addCriterion("relate_asset_type >", value, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("relate_asset_type >=", value, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeLessThan(String value) {
            addCriterion("relate_asset_type <", value, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeLessThanOrEqualTo(String value) {
            addCriterion("relate_asset_type <=", value, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeLike(String value) {
            addCriterion("relate_asset_type like", value, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeNotLike(String value) {
            addCriterion("relate_asset_type not like", value, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeIn(List<String> values) {
            addCriterion("relate_asset_type in", values, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeNotIn(List<String> values) {
            addCriterion("relate_asset_type not in", values, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeBetween(String value1, String value2) {
            addCriterion("relate_asset_type between", value1, value2, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetTypeNotBetween(String value1, String value2) {
            addCriterion("relate_asset_type not between", value1, value2, "relateAssetType");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdIsNull() {
            addCriterion("relate_asset_id is null");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdIsNotNull() {
            addCriterion("relate_asset_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdEqualTo(String value) {
            addCriterion("relate_asset_id =", value, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdNotEqualTo(String value) {
            addCriterion("relate_asset_id <>", value, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdGreaterThan(String value) {
            addCriterion("relate_asset_id >", value, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdGreaterThanOrEqualTo(String value) {
            addCriterion("relate_asset_id >=", value, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdLessThan(String value) {
            addCriterion("relate_asset_id <", value, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdLessThanOrEqualTo(String value) {
            addCriterion("relate_asset_id <=", value, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdLike(String value) {
            addCriterion("relate_asset_id like", value, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdNotLike(String value) {
            addCriterion("relate_asset_id not like", value, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdIn(List<String> values) {
            addCriterion("relate_asset_id in", values, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdNotIn(List<String> values) {
            addCriterion("relate_asset_id not in", values, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdBetween(String value1, String value2) {
            addCriterion("relate_asset_id between", value1, value2, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andRelateAssetIdNotBetween(String value1, String value2) {
            addCriterion("relate_asset_id not between", value1, value2, "relateAssetId");
            return (Criteria) this;
        }

        public Criteria andHappenDateIsNull() {
            addCriterion("happen_date is null");
            return (Criteria) this;
        }

        public Criteria andHappenDateIsNotNull() {
            addCriterion("happen_date is not null");
            return (Criteria) this;
        }

        public Criteria andHappenDateEqualTo(Date value) {
            addCriterion("happen_date =", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateNotEqualTo(Date value) {
            addCriterion("happen_date <>", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateGreaterThan(Date value) {
            addCriterion("happen_date >", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateGreaterThanOrEqualTo(Date value) {
            addCriterion("happen_date >=", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateLessThan(Date value) {
            addCriterion("happen_date <", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateLessThanOrEqualTo(Date value) {
            addCriterion("happen_date <=", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateIn(List<Date> values) {
            addCriterion("happen_date in", values, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateNotIn(List<Date> values) {
            addCriterion("happen_date not in", values, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateBetween(Date value1, Date value2) {
            addCriterion("happen_date between", value1, value2, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateNotBetween(Date value1, Date value2) {
            addCriterion("happen_date not between", value1, value2, "happenDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdIsNull() {
            addCriterion("recovery_event_id is null");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdIsNotNull() {
            addCriterion("recovery_event_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdEqualTo(String value) {
            addCriterion("recovery_event_id =", value, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdNotEqualTo(String value) {
            addCriterion("recovery_event_id <>", value, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdGreaterThan(String value) {
            addCriterion("recovery_event_id >", value, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdGreaterThanOrEqualTo(String value) {
            addCriterion("recovery_event_id >=", value, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdLessThan(String value) {
            addCriterion("recovery_event_id <", value, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdLessThanOrEqualTo(String value) {
            addCriterion("recovery_event_id <=", value, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdLike(String value) {
            addCriterion("recovery_event_id like", value, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdNotLike(String value) {
            addCriterion("recovery_event_id not like", value, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdIn(List<String> values) {
            addCriterion("recovery_event_id in", values, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdNotIn(List<String> values) {
            addCriterion("recovery_event_id not in", values, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdBetween(String value1, String value2) {
            addCriterion("recovery_event_id between", value1, value2, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryEventIdNotBetween(String value1, String value2) {
            addCriterion("recovery_event_id not between", value1, value2, "recoveryEventId");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateIsNull() {
            addCriterion("recovery_date is null");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateIsNotNull() {
            addCriterion("recovery_date is not null");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateEqualTo(Date value) {
            addCriterion("recovery_date =", value, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateNotEqualTo(Date value) {
            addCriterion("recovery_date <>", value, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateGreaterThan(Date value) {
            addCriterion("recovery_date >", value, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateGreaterThanOrEqualTo(Date value) {
            addCriterion("recovery_date >=", value, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateLessThan(Date value) {
            addCriterion("recovery_date <", value, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateLessThanOrEqualTo(Date value) {
            addCriterion("recovery_date <=", value, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateIn(List<Date> values) {
            addCriterion("recovery_date in", values, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateNotIn(List<Date> values) {
            addCriterion("recovery_date not in", values, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateBetween(Date value1, Date value2) {
            addCriterion("recovery_date between", value1, value2, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andRecoveryDateNotBetween(Date value1, Date value2) {
            addCriterion("recovery_date not between", value1, value2, "recoveryDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdIsNull() {
            addCriterion("work_order_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdIsNotNull() {
            addCriterion("work_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdEqualTo(String value) {
            addCriterion("work_order_id =", value, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdNotEqualTo(String value) {
            addCriterion("work_order_id <>", value, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdGreaterThan(String value) {
            addCriterion("work_order_id >", value, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("work_order_id >=", value, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdLessThan(String value) {
            addCriterion("work_order_id <", value, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdLessThanOrEqualTo(String value) {
            addCriterion("work_order_id <=", value, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdLike(String value) {
            addCriterion("work_order_id like", value, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdNotLike(String value) {
            addCriterion("work_order_id not like", value, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdIn(List<String> values) {
            addCriterion("work_order_id in", values, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdNotIn(List<String> values) {
            addCriterion("work_order_id not in", values, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdBetween(String value1, String value2) {
            addCriterion("work_order_id between", value1, value2, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andWorkOrderIdNotBetween(String value1, String value2) {
            addCriterion("work_order_id not between", value1, value2, "workOrderId");
            return (Criteria) this;
        }

        public Criteria andHostIpIsNull() {
            addCriterion("host_ip is null");
            return (Criteria) this;
        }

        public Criteria andHostIpIsNotNull() {
            addCriterion("host_ip is not null");
            return (Criteria) this;
        }

        public Criteria andHostIpEqualTo(String value) {
            addCriterion("host_ip =", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotEqualTo(String value) {
            addCriterion("host_ip <>", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpGreaterThan(String value) {
            addCriterion("host_ip >", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpGreaterThanOrEqualTo(String value) {
            addCriterion("host_ip >=", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpLessThan(String value) {
            addCriterion("host_ip <", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpLessThanOrEqualTo(String value) {
            addCriterion("host_ip <=", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpLike(String value) {
            addCriterion("host_ip like", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotLike(String value) {
            addCriterion("host_ip not like", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpIn(List<String> values) {
            addCriterion("host_ip in", values, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotIn(List<String> values) {
            addCriterion("host_ip not in", values, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpBetween(String value1, String value2) {
            addCriterion("host_ip between", value1, value2, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotBetween(String value1, String value2) {
            addCriterion("host_ip not between", value1, value2, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostNameIsNull() {
            addCriterion("host_name is null");
            return (Criteria) this;
        }

        public Criteria andHostNameIsNotNull() {
            addCriterion("host_name is not null");
            return (Criteria) this;
        }

        public Criteria andHostNameEqualTo(String value) {
            addCriterion("host_name =", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotEqualTo(String value) {
            addCriterion("host_name <>", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameGreaterThan(String value) {
            addCriterion("host_name >", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameGreaterThanOrEqualTo(String value) {
            addCriterion("host_name >=", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameLessThan(String value) {
            addCriterion("host_name <", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameLessThanOrEqualTo(String value) {
            addCriterion("host_name <=", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameLike(String value) {
            addCriterion("host_name like", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotLike(String value) {
            addCriterion("host_name not like", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameIn(List<String> values) {
            addCriterion("host_name in", values, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotIn(List<String> values) {
            addCriterion("host_name not in", values, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameBetween(String value1, String value2) {
            addCriterion("host_name between", value1, value2, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotBetween(String value1, String value2) {
            addCriterion("host_name not between", value1, value2, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostIdIsNull() {
            addCriterion("host_id is null");
            return (Criteria) this;
        }

        public Criteria andHostIdIsNotNull() {
            addCriterion("host_id is not null");
            return (Criteria) this;
        }

        public Criteria andHostIdEqualTo(String value) {
            addCriterion("host_id =", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotEqualTo(String value) {
            addCriterion("host_id <>", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdGreaterThan(String value) {
            addCriterion("host_id >", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdGreaterThanOrEqualTo(String value) {
            addCriterion("host_id >=", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdLessThan(String value) {
            addCriterion("host_id <", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdLessThanOrEqualTo(String value) {
            addCriterion("host_id <=", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdLike(String value) {
            addCriterion("host_id like", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotLike(String value) {
            addCriterion("host_id not like", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdIn(List<String> values) {
            addCriterion("host_id in", values, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotIn(List<String> values) {
            addCriterion("host_id not in", values, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdBetween(String value1, String value2) {
            addCriterion("host_id between", value1, value2, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotBetween(String value1, String value2) {
            addCriterion("host_id not between", value1, value2, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostPortIsNull() {
            addCriterion("host_port is null");
            return (Criteria) this;
        }

        public Criteria andHostPortIsNotNull() {
            addCriterion("host_port is not null");
            return (Criteria) this;
        }

        public Criteria andHostPortEqualTo(String value) {
            addCriterion("host_port =", value, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortNotEqualTo(String value) {
            addCriterion("host_port <>", value, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortGreaterThan(String value) {
            addCriterion("host_port >", value, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortGreaterThanOrEqualTo(String value) {
            addCriterion("host_port >=", value, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortLessThan(String value) {
            addCriterion("host_port <", value, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortLessThanOrEqualTo(String value) {
            addCriterion("host_port <=", value, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortLike(String value) {
            addCriterion("host_port like", value, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortNotLike(String value) {
            addCriterion("host_port not like", value, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortIn(List<String> values) {
            addCriterion("host_port in", values, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortNotIn(List<String> values) {
            addCriterion("host_port not in", values, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortBetween(String value1, String value2) {
            addCriterion("host_port between", value1, value2, "hostPort");
            return (Criteria) this;
        }

        public Criteria andHostPortNotBetween(String value1, String value2) {
            addCriterion("host_port not between", value1, value2, "hostPort");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(String value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(String value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(String value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(String value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(String value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLike(String value) {
            addCriterion("item_id like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotLike(String value) {
            addCriterion("item_id not like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<String> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<String> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(String value1, String value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(String value1, String value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("org_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("org_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(String value) {
            addCriterion("org_id =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(String value) {
            addCriterion("org_id <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(String value) {
            addCriterion("org_id >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("org_id >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(String value) {
            addCriterion("org_id <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(String value) {
            addCriterion("org_id <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLike(String value) {
            addCriterion("org_id like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotLike(String value) {
            addCriterion("org_id not like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<String> values) {
            addCriterion("org_id in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<String> values) {
            addCriterion("org_id not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(String value1, String value2) {
            addCriterion("org_id between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(String value1, String value2) {
            addCriterion("org_id not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andProblemDataIsNull() {
            addCriterion("problem_data is null");
            return (Criteria) this;
        }

        public Criteria andProblemDataIsNotNull() {
            addCriterion("problem_data is not null");
            return (Criteria) this;
        }

        public Criteria andProblemDataEqualTo(String value) {
            addCriterion("problem_data =", value, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataNotEqualTo(String value) {
            addCriterion("problem_data <>", value, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataGreaterThan(String value) {
            addCriterion("problem_data >", value, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataGreaterThanOrEqualTo(String value) {
            addCriterion("problem_data >=", value, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataLessThan(String value) {
            addCriterion("problem_data <", value, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataLessThanOrEqualTo(String value) {
            addCriterion("problem_data <=", value, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataLike(String value) {
            addCriterion("problem_data like", value, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataNotLike(String value) {
            addCriterion("problem_data not like", value, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataIn(List<String> values) {
            addCriterion("problem_data in", values, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataNotIn(List<String> values) {
            addCriterion("problem_data not in", values, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataBetween(String value1, String value2) {
            addCriterion("problem_data between", value1, value2, "problemData");
            return (Criteria) this;
        }

        public Criteria andProblemDataNotBetween(String value1, String value2) {
            addCriterion("problem_data not between", value1, value2, "problemData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataIsNull() {
            addCriterion("recovery_data is null");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataIsNotNull() {
            addCriterion("recovery_data is not null");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataEqualTo(String value) {
            addCriterion("recovery_data =", value, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataNotEqualTo(String value) {
            addCriterion("recovery_data <>", value, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataGreaterThan(String value) {
            addCriterion("recovery_data >", value, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataGreaterThanOrEqualTo(String value) {
            addCriterion("recovery_data >=", value, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataLessThan(String value) {
            addCriterion("recovery_data <", value, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataLessThanOrEqualTo(String value) {
            addCriterion("recovery_data <=", value, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataLike(String value) {
            addCriterion("recovery_data like", value, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataNotLike(String value) {
            addCriterion("recovery_data not like", value, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataIn(List<String> values) {
            addCriterion("recovery_data in", values, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataNotIn(List<String> values) {
            addCriterion("recovery_data not in", values, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataBetween(String value1, String value2) {
            addCriterion("recovery_data between", value1, value2, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andRecoveryDataNotBetween(String value1, String value2) {
            addCriterion("recovery_data not between", value1, value2, "recoveryData");
            return (Criteria) this;
        }

        public Criteria andSearchTypeIsNull() {
            addCriterion("search_type is null");
            return (Criteria) this;
        }

        public Criteria andSearchTypeIsNotNull() {
            addCriterion("search_type is not null");
            return (Criteria) this;
        }

        public Criteria andSearchTypeEqualTo(Integer value) {
            addCriterion("search_type =", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeNotEqualTo(Integer value) {
            addCriterion("search_type <>", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeGreaterThan(Integer value) {
            addCriterion("search_type >", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("search_type >=", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeLessThan(Integer value) {
            addCriterion("search_type <", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeLessThanOrEqualTo(Integer value) {
            addCriterion("search_type <=", value, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeIn(List<Integer> values) {
            addCriterion("search_type in", values, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeNotIn(List<Integer> values) {
            addCriterion("search_type not in", values, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeBetween(Integer value1, Integer value2) {
            addCriterion("search_type between", value1, value2, "searchType");
            return (Criteria) this;
        }

        public Criteria andSearchTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("search_type not between", value1, value2, "searchType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table problem
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 18 09:48:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table problem
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}