package com.example.demo.model;

public class StorageDeviceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.ID
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.ID
     *
     * @return the value of storage_device.ID
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.ID
     *
     * @param id the value for storage_device.ID
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_password
     *
     * @return the value of storage_device.sip_password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipPassword() {
        return sipPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_password
     *
     * @param sipPassword the value for storage_device.sip_password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipPassword(String sipPassword) {
        this.sipPassword = sipPassword == null ? null : sipPassword.trim();
    }
}