package com.example.demo.model;

import java.util.Date;

public class StorageDevice extends StorageDeviceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.device_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String deviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.national_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String nationalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.install_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date installTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.user_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.user_password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.device_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.manufacturer_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String manufacturerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.device_manufacture
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String deviceManufacture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.development_organization
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String developmentOrganization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.construction_unit
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String constructionUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.contact_person
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String contactPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.contact_mobile
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String contactMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.storage_channel
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer storageChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.coded_format
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String codedFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.storage_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String storageTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.storage_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String storageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer sipNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_domain
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipDomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_equipment_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipEquipmentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_local_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipLocalPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_register_indate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipRegisterIndate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_heartbeat_period
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipHeartbeatPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_max_heartbeat_overtime
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipMaxHeartbeatOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.sip_administrative_divisions
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sipAdministrativeDivisions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.access_module_identification_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String accessModuleIdentificationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.taskseq
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String taskseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.result
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_device.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer searchType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.device_name
     *
     * @return the value of storage_device.device_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.device_name
     *
     * @param deviceName the value for storage_device.device_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.national_code
     *
     * @return the value of storage_device.national_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getNationalCode() {
        return nationalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.national_code
     *
     * @param nationalCode the value for storage_device.national_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setNationalCode(String nationalCode) {
        this.nationalCode = nationalCode == null ? null : nationalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.install_time
     *
     * @return the value of storage_device.install_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getInstallTime() {
        return installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.install_time
     *
     * @param installTime the value for storage_device.install_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setInstallTime(Date installTime) {
        this.installTime = installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.ip
     *
     * @return the value of storage_device.ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.ip
     *
     * @param ip the value for storage_device.ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.port
     *
     * @return the value of storage_device.port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.port
     *
     * @param port the value for storage_device.port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.user_name
     *
     * @return the value of storage_device.user_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.user_name
     *
     * @param userName the value for storage_device.user_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.user_password
     *
     * @return the value of storage_device.user_password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.user_password
     *
     * @param userPassword the value for storage_device.user_password
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.device_type
     *
     * @return the value of storage_device.device_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.device_type
     *
     * @param deviceType the value for storage_device.device_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.manufacturer_id
     *
     * @return the value of storage_device.manufacturer_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getManufacturerId() {
        return manufacturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.manufacturer_id
     *
     * @param manufacturerId the value for storage_device.manufacturer_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setManufacturerId(String manufacturerId) {
        this.manufacturerId = manufacturerId == null ? null : manufacturerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.device_manufacture
     *
     * @return the value of storage_device.device_manufacture
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDeviceManufacture() {
        return deviceManufacture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.device_manufacture
     *
     * @param deviceManufacture the value for storage_device.device_manufacture
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDeviceManufacture(String deviceManufacture) {
        this.deviceManufacture = deviceManufacture == null ? null : deviceManufacture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.development_organization
     *
     * @return the value of storage_device.development_organization
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDevelopmentOrganization() {
        return developmentOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.development_organization
     *
     * @param developmentOrganization the value for storage_device.development_organization
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDevelopmentOrganization(String developmentOrganization) {
        this.developmentOrganization = developmentOrganization == null ? null : developmentOrganization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.construction_unit
     *
     * @return the value of storage_device.construction_unit
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getConstructionUnit() {
        return constructionUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.construction_unit
     *
     * @param constructionUnit the value for storage_device.construction_unit
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setConstructionUnit(String constructionUnit) {
        this.constructionUnit = constructionUnit == null ? null : constructionUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.contact_person
     *
     * @return the value of storage_device.contact_person
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.contact_person
     *
     * @param contactPerson the value for storage_device.contact_person
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.contact_mobile
     *
     * @return the value of storage_device.contact_mobile
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.contact_mobile
     *
     * @param contactMobile the value for storage_device.contact_mobile
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile == null ? null : contactMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.storage_channel
     *
     * @return the value of storage_device.storage_channel
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getStorageChannel() {
        return storageChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.storage_channel
     *
     * @param storageChannel the value for storage_device.storage_channel
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setStorageChannel(Integer storageChannel) {
        this.storageChannel = storageChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.coded_format
     *
     * @return the value of storage_device.coded_format
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCodedFormat() {
        return codedFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.coded_format
     *
     * @param codedFormat the value for storage_device.coded_format
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCodedFormat(String codedFormat) {
        this.codedFormat = codedFormat == null ? null : codedFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.storage_time
     *
     * @return the value of storage_device.storage_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getStorageTime() {
        return storageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.storage_time
     *
     * @param storageTime the value for storage_device.storage_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setStorageTime(String storageTime) {
        this.storageTime = storageTime == null ? null : storageTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.storage_type
     *
     * @return the value of storage_device.storage_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getStorageType() {
        return storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.storage_type
     *
     * @param storageType the value for storage_device.storage_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setStorageType(String storageType) {
        this.storageType = storageType == null ? null : storageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.project_id
     *
     * @return the value of storage_device.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.project_id
     *
     * @param projectId the value for storage_device.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.create_by
     *
     * @return the value of storage_device.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.create_by
     *
     * @param createBy the value for storage_device.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.create_date
     *
     * @return the value of storage_device.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.create_date
     *
     * @param createDate the value for storage_device.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.update_by
     *
     * @return the value of storage_device.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.update_by
     *
     * @param updateBy the value for storage_device.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.update_date
     *
     * @return the value of storage_device.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.update_date
     *
     * @param updateDate the value for storage_device.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.remarks
     *
     * @return the value of storage_device.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.remarks
     *
     * @param remarks the value for storage_device.remarks
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_number
     *
     * @return the value of storage_device.sip_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getSipNumber() {
        return sipNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_number
     *
     * @param sipNumber the value for storage_device.sip_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipNumber(Integer sipNumber) {
        this.sipNumber = sipNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_domain
     *
     * @return the value of storage_device.sip_domain
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipDomain() {
        return sipDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_domain
     *
     * @param sipDomain the value for storage_device.sip_domain
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipDomain(String sipDomain) {
        this.sipDomain = sipDomain == null ? null : sipDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_ip
     *
     * @return the value of storage_device.sip_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipIp() {
        return sipIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_ip
     *
     * @param sipIp the value for storage_device.sip_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipIp(String sipIp) {
        this.sipIp = sipIp == null ? null : sipIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_port
     *
     * @return the value of storage_device.sip_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipPort() {
        return sipPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_port
     *
     * @param sipPort the value for storage_device.sip_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipPort(String sipPort) {
        this.sipPort = sipPort == null ? null : sipPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_equipment_number
     *
     * @return the value of storage_device.sip_equipment_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipEquipmentNumber() {
        return sipEquipmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_equipment_number
     *
     * @param sipEquipmentNumber the value for storage_device.sip_equipment_number
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipEquipmentNumber(String sipEquipmentNumber) {
        this.sipEquipmentNumber = sipEquipmentNumber == null ? null : sipEquipmentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_local_port
     *
     * @return the value of storage_device.sip_local_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipLocalPort() {
        return sipLocalPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_local_port
     *
     * @param sipLocalPort the value for storage_device.sip_local_port
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipLocalPort(String sipLocalPort) {
        this.sipLocalPort = sipLocalPort == null ? null : sipLocalPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_register_indate
     *
     * @return the value of storage_device.sip_register_indate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipRegisterIndate() {
        return sipRegisterIndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_register_indate
     *
     * @param sipRegisterIndate the value for storage_device.sip_register_indate
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipRegisterIndate(String sipRegisterIndate) {
        this.sipRegisterIndate = sipRegisterIndate == null ? null : sipRegisterIndate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_heartbeat_period
     *
     * @return the value of storage_device.sip_heartbeat_period
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipHeartbeatPeriod() {
        return sipHeartbeatPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_heartbeat_period
     *
     * @param sipHeartbeatPeriod the value for storage_device.sip_heartbeat_period
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipHeartbeatPeriod(String sipHeartbeatPeriod) {
        this.sipHeartbeatPeriod = sipHeartbeatPeriod == null ? null : sipHeartbeatPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_max_heartbeat_overtime
     *
     * @return the value of storage_device.sip_max_heartbeat_overtime
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipMaxHeartbeatOvertime() {
        return sipMaxHeartbeatOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_max_heartbeat_overtime
     *
     * @param sipMaxHeartbeatOvertime the value for storage_device.sip_max_heartbeat_overtime
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipMaxHeartbeatOvertime(String sipMaxHeartbeatOvertime) {
        this.sipMaxHeartbeatOvertime = sipMaxHeartbeatOvertime == null ? null : sipMaxHeartbeatOvertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.sip_administrative_divisions
     *
     * @return the value of storage_device.sip_administrative_divisions
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSipAdministrativeDivisions() {
        return sipAdministrativeDivisions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.sip_administrative_divisions
     *
     * @param sipAdministrativeDivisions the value for storage_device.sip_administrative_divisions
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSipAdministrativeDivisions(String sipAdministrativeDivisions) {
        this.sipAdministrativeDivisions = sipAdministrativeDivisions == null ? null : sipAdministrativeDivisions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.access_module_identification_code
     *
     * @return the value of storage_device.access_module_identification_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getAccessModuleIdentificationCode() {
        return accessModuleIdentificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.access_module_identification_code
     *
     * @param accessModuleIdentificationCode the value for storage_device.access_module_identification_code
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setAccessModuleIdentificationCode(String accessModuleIdentificationCode) {
        this.accessModuleIdentificationCode = accessModuleIdentificationCode == null ? null : accessModuleIdentificationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.org_id
     *
     * @return the value of storage_device.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.org_id
     *
     * @param orgId the value for storage_device.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.taskseq
     *
     * @return the value of storage_device.taskseq
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getTaskseq() {
        return taskseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.taskseq
     *
     * @param taskseq the value for storage_device.taskseq
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setTaskseq(String taskseq) {
        this.taskseq = taskseq == null ? null : taskseq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.del_flag
     *
     * @return the value of storage_device.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.del_flag
     *
     * @param delFlag the value for storage_device.del_flag
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.result
     *
     * @return the value of storage_device.result
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.result
     *
     * @param result the value for storage_device.result
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.description
     *
     * @return the value of storage_device.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.description
     *
     * @param description the value for storage_device.description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_device.search_type
     *
     * @return the value of storage_device.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getSearchType() {
        return searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_device.search_type
     *
     * @param searchType the value for storage_device.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }
}