package com.example.demo.model;

import java.util.Date;

public class WorkOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.sn
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.title
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.relate_asset_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String relateAssetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.relate_asset_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String relateAssetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.relate_asset_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String relateAssetIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.relate_device_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String relateDeviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.problem_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.problem_title
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String problemTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.problem_description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String problemDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.project_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.department_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.department_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.level
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.trigger_user_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String triggerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.trigger_user_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String triggerUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.current_handler_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String currentHandlerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.current_handler_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String currentHandlerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.duration
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Long duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.handup_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Long handupTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.respond_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Long respondTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.problem_start_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date problemStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.problem_end_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date problemEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.handup
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Boolean handup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.handup_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date handupDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.handup_reason
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String handupReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.fault_source
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String faultSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.fault_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String faultType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.receive_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date receiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.arrive_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date arriveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.report_repair_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date reportRepairDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.repair_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date repairDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.repair_confirmer
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String repairConfirmer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.repair_confirm_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date repairConfirmDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.readed
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Boolean readed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.contact
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.telPhone
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.img_urls
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String imgUrls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.handup_apply
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Boolean handupApply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    private Integer searchType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.id
     *
     * @return the value of work_order.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.id
     *
     * @param id the value for work_order.id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.sn
     *
     * @return the value of work_order.sn
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.sn
     *
     * @param sn the value for work_order.sn
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.title
     *
     * @return the value of work_order.title
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.title
     *
     * @param title the value for work_order.title
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.type
     *
     * @return the value of work_order.type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.type
     *
     * @param type the value for work_order.type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.relate_asset_type
     *
     * @return the value of work_order.relate_asset_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRelateAssetType() {
        return relateAssetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.relate_asset_type
     *
     * @param relateAssetType the value for work_order.relate_asset_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRelateAssetType(String relateAssetType) {
        this.relateAssetType = relateAssetType == null ? null : relateAssetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.relate_asset_id
     *
     * @return the value of work_order.relate_asset_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRelateAssetId() {
        return relateAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.relate_asset_id
     *
     * @param relateAssetId the value for work_order.relate_asset_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRelateAssetId(String relateAssetId) {
        this.relateAssetId = relateAssetId == null ? null : relateAssetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.relate_asset_ip
     *
     * @return the value of work_order.relate_asset_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRelateAssetIp() {
        return relateAssetIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.relate_asset_ip
     *
     * @param relateAssetIp the value for work_order.relate_asset_ip
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRelateAssetIp(String relateAssetIp) {
        this.relateAssetIp = relateAssetIp == null ? null : relateAssetIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.relate_device_type
     *
     * @return the value of work_order.relate_device_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRelateDeviceType() {
        return relateDeviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.relate_device_type
     *
     * @param relateDeviceType the value for work_order.relate_device_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRelateDeviceType(String relateDeviceType) {
        this.relateDeviceType = relateDeviceType == null ? null : relateDeviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.problem_id
     *
     * @return the value of work_order.problem_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.problem_id
     *
     * @param problemId the value for work_order.problem_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProblemId(String problemId) {
        this.problemId = problemId == null ? null : problemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.problem_title
     *
     * @return the value of work_order.problem_title
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProblemTitle() {
        return problemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.problem_title
     *
     * @param problemTitle the value for work_order.problem_title
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProblemTitle(String problemTitle) {
        this.problemTitle = problemTitle == null ? null : problemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.problem_description
     *
     * @return the value of work_order.problem_description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProblemDescription() {
        return problemDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.problem_description
     *
     * @param problemDescription the value for work_order.problem_description
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProblemDescription(String problemDescription) {
        this.problemDescription = problemDescription == null ? null : problemDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.status
     *
     * @return the value of work_order.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.status
     *
     * @param status the value for work_order.status
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.project_id
     *
     * @return the value of work_order.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.project_id
     *
     * @param projectId the value for work_order.project_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.project_name
     *
     * @return the value of work_order.project_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.project_name
     *
     * @param projectName the value for work_order.project_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.department_id
     *
     * @return the value of work_order.department_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.department_id
     *
     * @param departmentId the value for work_order.department_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.department_name
     *
     * @return the value of work_order.department_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.department_name
     *
     * @param departmentName the value for work_order.department_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.level
     *
     * @return the value of work_order.level
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.level
     *
     * @param level the value for work_order.level
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.trigger_user_id
     *
     * @return the value of work_order.trigger_user_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getTriggerUserId() {
        return triggerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.trigger_user_id
     *
     * @param triggerUserId the value for work_order.trigger_user_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setTriggerUserId(String triggerUserId) {
        this.triggerUserId = triggerUserId == null ? null : triggerUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.trigger_user_name
     *
     * @return the value of work_order.trigger_user_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getTriggerUserName() {
        return triggerUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.trigger_user_name
     *
     * @param triggerUserName the value for work_order.trigger_user_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setTriggerUserName(String triggerUserName) {
        this.triggerUserName = triggerUserName == null ? null : triggerUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.current_handler_id
     *
     * @return the value of work_order.current_handler_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCurrentHandlerId() {
        return currentHandlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.current_handler_id
     *
     * @param currentHandlerId the value for work_order.current_handler_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCurrentHandlerId(String currentHandlerId) {
        this.currentHandlerId = currentHandlerId == null ? null : currentHandlerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.current_handler_name
     *
     * @return the value of work_order.current_handler_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCurrentHandlerName() {
        return currentHandlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.current_handler_name
     *
     * @param currentHandlerName the value for work_order.current_handler_name
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCurrentHandlerName(String currentHandlerName) {
        this.currentHandlerName = currentHandlerName == null ? null : currentHandlerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.duration
     *
     * @return the value of work_order.duration
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.duration
     *
     * @param duration the value for work_order.duration
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.handup_time
     *
     * @return the value of work_order.handup_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Long getHandupTime() {
        return handupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.handup_time
     *
     * @param handupTime the value for work_order.handup_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHandupTime(Long handupTime) {
        this.handupTime = handupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.respond_time
     *
     * @return the value of work_order.respond_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Long getRespondTime() {
        return respondTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.respond_time
     *
     * @param respondTime the value for work_order.respond_time
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRespondTime(Long respondTime) {
        this.respondTime = respondTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.problem_start_date
     *
     * @return the value of work_order.problem_start_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getProblemStartDate() {
        return problemStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.problem_start_date
     *
     * @param problemStartDate the value for work_order.problem_start_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProblemStartDate(Date problemStartDate) {
        this.problemStartDate = problemStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.problem_end_date
     *
     * @return the value of work_order.problem_end_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getProblemEndDate() {
        return problemEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.problem_end_date
     *
     * @param problemEndDate the value for work_order.problem_end_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setProblemEndDate(Date problemEndDate) {
        this.problemEndDate = problemEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.handup
     *
     * @return the value of work_order.handup
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Boolean getHandup() {
        return handup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.handup
     *
     * @param handup the value for work_order.handup
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHandup(Boolean handup) {
        this.handup = handup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.handup_date
     *
     * @return the value of work_order.handup_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getHandupDate() {
        return handupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.handup_date
     *
     * @param handupDate the value for work_order.handup_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHandupDate(Date handupDate) {
        this.handupDate = handupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.handup_reason
     *
     * @return the value of work_order.handup_reason
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getHandupReason() {
        return handupReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.handup_reason
     *
     * @param handupReason the value for work_order.handup_reason
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHandupReason(String handupReason) {
        this.handupReason = handupReason == null ? null : handupReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.fault_source
     *
     * @return the value of work_order.fault_source
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getFaultSource() {
        return faultSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.fault_source
     *
     * @param faultSource the value for work_order.fault_source
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setFaultSource(String faultSource) {
        this.faultSource = faultSource == null ? null : faultSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.fault_type
     *
     * @return the value of work_order.fault_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getFaultType() {
        return faultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.fault_type
     *
     * @param faultType the value for work_order.fault_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setFaultType(String faultType) {
        this.faultType = faultType == null ? null : faultType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.receive_date
     *
     * @return the value of work_order.receive_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getReceiveDate() {
        return receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.receive_date
     *
     * @param receiveDate the value for work_order.receive_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.arrive_date
     *
     * @return the value of work_order.arrive_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getArriveDate() {
        return arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.arrive_date
     *
     * @param arriveDate the value for work_order.arrive_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setArriveDate(Date arriveDate) {
        this.arriveDate = arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.report_repair_date
     *
     * @return the value of work_order.report_repair_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getReportRepairDate() {
        return reportRepairDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.report_repair_date
     *
     * @param reportRepairDate the value for work_order.report_repair_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setReportRepairDate(Date reportRepairDate) {
        this.reportRepairDate = reportRepairDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.repair_date
     *
     * @return the value of work_order.repair_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getRepairDate() {
        return repairDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.repair_date
     *
     * @param repairDate the value for work_order.repair_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRepairDate(Date repairDate) {
        this.repairDate = repairDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.repair_confirmer
     *
     * @return the value of work_order.repair_confirmer
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getRepairConfirmer() {
        return repairConfirmer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.repair_confirmer
     *
     * @param repairConfirmer the value for work_order.repair_confirmer
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRepairConfirmer(String repairConfirmer) {
        this.repairConfirmer = repairConfirmer == null ? null : repairConfirmer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.repair_confirm_date
     *
     * @return the value of work_order.repair_confirm_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getRepairConfirmDate() {
        return repairConfirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.repair_confirm_date
     *
     * @param repairConfirmDate the value for work_order.repair_confirm_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setRepairConfirmDate(Date repairConfirmDate) {
        this.repairConfirmDate = repairConfirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.readed
     *
     * @return the value of work_order.readed
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Boolean getReaded() {
        return readed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.readed
     *
     * @param readed the value for work_order.readed
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setReaded(Boolean readed) {
        this.readed = readed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.contact
     *
     * @return the value of work_order.contact
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.contact
     *
     * @param contact the value for work_order.contact
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.telPhone
     *
     * @return the value of work_order.telPhone
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.telPhone
     *
     * @param telphone the value for work_order.telPhone
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.img_urls
     *
     * @return the value of work_order.img_urls
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getImgUrls() {
        return imgUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.img_urls
     *
     * @param imgUrls the value for work_order.img_urls
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setImgUrls(String imgUrls) {
        this.imgUrls = imgUrls == null ? null : imgUrls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.create_by
     *
     * @return the value of work_order.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.create_by
     *
     * @param createBy the value for work_order.create_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.create_date
     *
     * @return the value of work_order.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.create_date
     *
     * @param createDate the value for work_order.create_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.update_by
     *
     * @return the value of work_order.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.update_by
     *
     * @param updateBy the value for work_order.update_by
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.update_date
     *
     * @return the value of work_order.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.update_date
     *
     * @param updateDate the value for work_order.update_date
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.org_id
     *
     * @return the value of work_order.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.org_id
     *
     * @param orgId the value for work_order.org_id
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.handup_apply
     *
     * @return the value of work_order.handup_apply
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Boolean getHandupApply() {
        return handupApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.handup_apply
     *
     * @param handupApply the value for work_order.handup_apply
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setHandupApply(Boolean handupApply) {
        this.handupApply = handupApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.search_type
     *
     * @return the value of work_order.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public Integer getSearchType() {
        return searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.search_type
     *
     * @param searchType the value for work_order.search_type
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }
}