package com.example.demo.mapper;

import com.example.demo.model.AssetSwitcher;
import com.example.demo.model.AssetSwitcherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetSwitcherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    long countByExample(AssetSwitcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByExample(AssetSwitcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insert(AssetSwitcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insertSelective(AssetSwitcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    List<AssetSwitcher> selectByExample(AssetSwitcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    AssetSwitcher selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") AssetSwitcher record, @Param("example") AssetSwitcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExample(@Param("record") AssetSwitcher record, @Param("example") AssetSwitcherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKeySelective(AssetSwitcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_switcher
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKey(AssetSwitcher record);
}