package com.example.demo.mapper;

import com.example.demo.model.AssetRouter;
import com.example.demo.model.AssetRouterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetRouterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    long countByExample(AssetRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByExample(AssetRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insert(AssetRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insertSelective(AssetRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    List<AssetRouter> selectByExample(AssetRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    AssetRouter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") AssetRouter record, @Param("example") AssetRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExample(@Param("record") AssetRouter record, @Param("example") AssetRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKeySelective(AssetRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_router
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKey(AssetRouter record);
}