package com.example.demo.mapper;

import com.example.demo.model.AssetHostDevice;
import com.example.demo.model.AssetHostDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetHostDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    long countByExample(AssetHostDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByExample(AssetHostDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insert(AssetHostDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insertSelective(AssetHostDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    List<AssetHostDevice> selectByExample(AssetHostDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    AssetHostDevice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") AssetHostDevice record, @Param("example") AssetHostDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExample(@Param("record") AssetHostDevice record, @Param("example") AssetHostDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKeySelective(AssetHostDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_host_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKey(AssetHostDevice record);
}