package com.example.demo.mapper;

import com.example.demo.model.AssetMysql;
import com.example.demo.model.AssetMysqlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetMysqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    long countByExample(AssetMysqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByExample(AssetMysqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insert(AssetMysql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insertSelective(AssetMysql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    List<AssetMysql> selectByExample(AssetMysqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    AssetMysql selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") AssetMysql record, @Param("example") AssetMysqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExample(@Param("record") AssetMysql record, @Param("example") AssetMysqlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKeySelective(AssetMysql record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_mysql
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKey(AssetMysql record);
}