package com.example.demo.mapper;

import com.example.demo.model.Encoder;
import com.example.demo.model.EncoderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EncoderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    long countByExample(EncoderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByExample(EncoderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insert(Encoder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insertSelective(Encoder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    List<Encoder> selectByExample(EncoderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    Encoder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") Encoder record, @Param("example") EncoderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExample(@Param("record") Encoder record, @Param("example") EncoderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKeySelective(Encoder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encoder
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKey(Encoder record);
}