package com.example.demo.mapper;

import com.example.demo.model.StorageDevice;
import com.example.demo.model.StorageDeviceExample;
import com.example.demo.model.StorageDeviceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StorageDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    long countByExample(StorageDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByExample(StorageDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int deleteByPrimaryKey(StorageDeviceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insert(StorageDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int insertSelective(StorageDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    List<StorageDevice> selectByExample(StorageDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    StorageDevice selectByPrimaryKey(StorageDeviceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") StorageDevice record, @Param("example") StorageDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByExample(@Param("record") StorageDevice record, @Param("example") StorageDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKeySelective(StorageDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_device
     *
     * @mbg.generated Wed Jul 18 09:48:47 CST 2018
     */
    int updateByPrimaryKey(StorageDevice record);
}